/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/productsList': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Retrieve all products
     * @description Returns complete product catalog with details including:
     *     - Product ID, name, price
     *     - Brand information
     *     - Category hierarchy (usertype -> category)
     *
     *     **Performance SLO**: P50 < 800ms, P95 < 1500ms
     */
    get: operations['getProductsList'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/brandsList': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Retrieve all brands
     * @description Returns list of all available product brands
     *
     *     **Performance SLO**: P50 < 600ms, P95 < 1200ms
     */
    get: operations['getBrandsList'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/searchProduct': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Search for products
     * @description Search products by name or description
     *     Returns filtered product list matching search criteria
     *
     *     **Performance SLO**: P50 < 1000ms, P95 < 2000ms
     *
     *     **Note**: API accepts form-urlencoded data, not JSON
     */
    post: operations['searchProducts'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Product: {
      /**
       * @description Unique product identifier
       * @example 1
       */
      id: number;
      /**
       * @description Product name
       * @example Blue Top
       */
      name: string;
      /**
       * @description Product price with currency
       * @example Rs. 500
       */
      price: string;
      /**
       * @description Brand name
       * @example Polo
       */
      brand: string;
      category: components['schemas']['Category'];
    };
    Category: {
      usertype: {
        /**
         * @description Target demographic
         * @enum {string}
         */
        usertype: 'Women' | 'Men' | 'Kids';
      };
      /**
       * @description Product category
       * @example Tops
       */
      category: string;
    };
    Brand: {
      /**
       * @description Unique brand identifier
       * @example 1
       */
      id: number;
      /**
       * @description Brand name
       * @example Polo
       */
      brand: string;
    };
    ProductsListResponse: {
      /**
       * @description HTTP status code
       * @enum {integer}
       */
      responseCode: 200;
      /** @description Array of product objects */
      products: components['schemas']['Product'][];
    };
    BrandsListResponse: {
      /**
       * @description HTTP status code
       * @enum {integer}
       */
      responseCode: 200;
      /** @description Array of brand objects */
      brands: components['schemas']['Brand'][];
    };
    SearchProductsResponse: {
      /**
       * @description HTTP status code
       * @enum {integer}
       */
      responseCode: 200;
      /** @description Array of matching products (empty if no matches) */
      products: components['schemas']['Product'][];
    };
    ErrorResponse: {
      /**
       * @description HTTP error status code
       * @example 500
       */
      responseCode: number;
      /**
       * @description Error message
       * @example Internal Server Error
       */
      message: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getProductsList: {
    parameters: {
      query?: {
        /** @description Page number for pagination (not officially documented, may not be implemented) */
        page?: number;
        /** @description Items per page (not officially documented, may not be implemented) */
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response with product list */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProductsListResponse'];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  getBrandsList: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful response with brand list */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BrandsListResponse'];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  searchProducts: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/x-www-form-urlencoded': {
          /**
           * @description Search term for product name/description
           * @example dress
           */
          search_product: string;
        };
      };
    };
    responses: {
      /** @description Successful search results */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SearchProductsResponse'];
        };
      };
      /** @description Bad request (missing search_product parameter) */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
}
